stages:
- test
- run

variables:
  SLACK_TOKEN: ''
  SLACK_CHANNEL: ''

report_lunches:
  tags:
    - docker
  stage: run
  image: python:3.7
  script:
  - python setup.py install
  - python -m prglunch --slack-token "${SLACK_TOKEN}" --slack-channel "${SLACK_CHANNEL}"
  only:
    - schedules

test:
  tags:
    - docker
  stage: test
  image: python:3.7
  script:
  - python setup.py test
  except:
    - schedules
  when: manual
